version: '3.8'

services:
  mariadb:
    build: ./mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - backend

  maxscale:
    build: ./maxscale
    depends_on:
      - mariadb
    ports:
      - "3306:3306"
    networks:
      - backend

  keycloak:
    build: ./keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8080:8080"
    networks:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - backend
    depends_on:
      - keycloak
      - maxscale

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - frontend
    depends_on:
      - backend

networks:
  backend:
  frontend:

volumes:
  mariadb_data:
